apiVersion: apps/v1
kind: Deployment
metadata:
  name: medcare-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /medcare-openapi
            - name: BASE_URL
              value: /medcare-openapi-ui