apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: danielcok17/medcare-ufe
  newName: danielcok17/medcare-ufe
  newTag: 1.2.0  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: danielcok17/medcare-webapi
  newName: danielcok17/medcare-webapi
  newTag: 1.1.2

replacements:
 - targets:
   - select:
         group: fe.milung.eu
         version: v1
         kind: WebComponent
         name: medcare-ambulance-ufe
    #  fieldPaths:
    #      - spec.hash-suffix
   source:
     version: v1
     kind: Deployment
     name:  medcare-ambulance-ufe-deployment
     fieldPath: spec.template.spec.containers.0.image
     options:
         delimiter: ':'
         index: 1