apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: medcare-ambulance-ufe
spec:
  module-uri: http://medcare-ambulance-ufe.wac-hospital/build/medcare-ufe.esm.js
  # module-uri: http://xbalcercik-ambulance-ufe.wac-hospital/build/reko-ufe.esm.js

                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: medcare-homescreen    # element, ktorý bude vložený na stránku medcare-medical-app or medcare-ambulance-wl-app
                                    # pri navigácii na zoznam čakajúcich
      attributes:
      - name: api-base
        value: /medcare-api
      # - name: ambulance-id
      #   value: bobulova
      path: medcare      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny medcare-ambulance-wl  or medical
      title: MedCare     # názov mikro aplikácie
      details: Správa lekárskej dokumentácie v rámci jednotlivých ambulancií
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  # hash-suffix: v1alpha1           # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach